### ISSUE TITLE
Propozycja rozbudowy

### ISSUE THREAD

**Issue by hejsiri** [bfaliszek/homebridge-smogomierz#1]
Na wstępie gratuluję świetnej roboty :) Plugin działa jak należy. Zbudowałem swój smogomierz z czujnikiem PMS7003 i BME280. Mój czujnik jest już na mapie. W aplikacji DOM brakuje mi tylko wyciągnięcia temperatury i wilgotności z czujnika jako osobne kafelki. Byłoby super :)

**Comment by bfaliszek** [comment]
To prawda. Muszę to jeszcze dodać. Podobnie z ciśnieniem powietrza.

**Comment by hejsiri** [comment]
Super, czekam z niecierpliwością :)

**Comment by straubus** [comment]
Znalazłem takie pluginy, 
https://www.npmjs.com/package/homebridge-http-humidity      i taki https://www.npmjs.com/package/homebridge-http-temperature, i wyciąga dane ze smogomierz.local/api... i wrzuca je do homekit, ale to nadal dwa dodatkowe pluginy, może da się to dorzucić do głównego?

**Comment by hejsiri** [comment]
Da się na pewno, bo tak jest zrobiony chociażby plugin do Xiaomi Air Purifier. Jeden plugin, jeden oczyszczacz a dodaje 6 akcesoriów, m.in. temperatura i wilgotność. Poszedłbym tą drogą :) Musimy się po prostu ładnie uśmiechnąć do @bfaliszek  :-)
Plugin do oczyszczacza: https://github.com/seikan/homebridge-mi-air-purifier Można coś tam podpatrzeć :-)

![ad1e3c6b-9e67-4759-b42c-0a9e05a350f1](https://user-images.githubusercontent.com/37380727/51590770-5bee4300-1eeb-11e9-830a-b2d03182bb19.png)

**Comment by hejsiri** [comment]
Po aktualizacji nie działa.

**Comment by straubus** [comment]
W moim przypadku wymagało do działania wersji node >11.0.0

**Comment by hejsiri** [comment]
Na to wygląda...

> Plugin /usr/lib/node_modules/homebridge-smogomierz requires Node version of >=11.9.0 which does not satisfy the current Node version of v11.4.0. You may need to upgrade your installation of Node.

**Comment by hejsiri** [comment]
No niestety HomeBridge się wykłada mimo najnowszej wersji NODE 11.9.0

```
Feb 14 01:57:10 raspberrypi homebridge[1047]: [2/14/2019, 1:57:10 AM] [Smogomierz] Smogomierz is working
Feb 14 01:57:10 raspberrypi homebridge[1047]: /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:75
Feb 14 01:57:10 raspberrypi homebridge[1047]:     if (existing.UUID === characteristic.UUID) {
Feb 14 01:57:10 raspberrypi homebridge[1047]:                                          ^
Feb 14 01:57:10 raspberrypi homebridge[1047]: TypeError: Cannot read property 'UUID' of undefined
Feb 14 01:57:10 raspberrypi homebridge[1047]:     at Service.AirQualitySensor.Service.addCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:75:42)
Feb 14 01:57:10 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Feb 14 01:57:10 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Feb 14 01:57:10 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

**Comment by mickelk** [comment]
> No niestety HomeBridge się wykłada mimo najnowszej wersji NODE 11.9.0
> 
> ```
> Feb 14 01:57:10 raspberrypi homebridge[1047]: [2/14/2019, 1:57:10 AM] [Smogomierz] Smogomierz is working
> Feb 14 01:57:10 raspberrypi homebridge[1047]: /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:75
> Feb 14 01:57:10 raspberrypi homebridge[1047]:     if (existing.UUID === characteristic.UUID) {
> Feb 14 01:57:10 raspberrypi homebridge[1047]:                                          ^
> Feb 14 01:57:10 raspberrypi homebridge[1047]: TypeError: Cannot read property 'UUID' of undefined
> Feb 14 01:57:10 raspberrypi homebridge[1047]:     at Service.AirQualitySensor.Service.addCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:75:42)
> Feb 14 01:57:10 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
> Feb 14 01:57:10 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
> Feb 14 01:57:10 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
> ```

mam ten sam problem, wgraj sobie starsza wersję poleceniem
sudo npm install -g homebridge-smogomierz@1.1.3

**Comment by hejsiri** [comment]
Coś mu nie pasują te charakterystyki. U kogoś to działa? Możecie pokazać jakiegoś screen'a z tymi charakterystykami w szczegółach akcesorium?

**Comment by hejsiri** [comment]
> Znalazłem takie pluginy,
> https://www.npmjs.com/package/homebridge-http-humidity i taki https://www.npmjs.com/package/homebridge-http-temperature, i wyciąga dane ze smogomierz.local/api... i wrzuca je do homekit, ale to nadal dwa dodatkowe pluginy, może da się to dorzucić do głównego?

Możesz pokazać swojego konfiga? Pojęcia nie mam jak te dane wyciągnąć ze smogomierza.

**Comment by mickelk** [comment]
>        

 {
            "accessory": "HttpTemperature",
            "name": "Outside Temperature",
            "url": "http://IP/api",
            "http_method": "GET",
            "field_name": "temperature"
        },
        {
            "accessory": "HttpHumidity",
            "name": "Outside Humidity",
            "url": "http://IP/api",
            "http_method": "GET",
            "field_name": "humidity"
        }

>

**Comment by hejsiri** [comment]
Dziękuję dobry człowieku :)

**Comment by mickelk** [comment]
> Coś mu nie pasują te charakterystyki. U kogoś to działa? Możecie pokazać jakiegoś screen'a z tymi charakterystykami w szczegółach 

powiedz jak mam to sprawdzić to podeśle :)

**Comment by hejsiri** [comment]
Przytrzymujesz akcesorium smogomierz... ustawienia... i tu screenshota

**Comment by mickelk** [comment]
o to chodzi?

![](https://i.ibb.co/xs8Bnqw/IMG-0050.png)

**Comment by hejsiri** [comment]
Tak, a którą wersje pluginu masz?

**Comment by mickelk** [comment]
zainstalowaną 1.1.3, jak zainstaluje 1.2 to homebridge nie startuje i nie działa

**Comment by hejsiri** [comment]
Tak jak u mnie. W kodzie 1.2 jest dodana charakterystyka ciśnienia, temperatury i wilgotności, ale coś nie działa. Nie wiem gdzie powinno to pokazać (temperaturę i wilgotność) w szczegółach czy jako nowe kafelki w aplikacji. Ale to już pytanie do autora :)

**Comment by mickelk** [comment]
to czekamy na odpowiedź autora 👍

**Comment by bfaliszek** [comment]
Hej. Teoretycznie nie powinno ich(temp, wilgotności i ciśnienia) nigdzie pokazywać. Wydaje mi się, że problemem jest to, że przy 1.2 zaktualizowałem wszystkie wymagane biblioteki do najnowszych wersji. Na moim zestawie testowym, gdzie miałem wcześniej 1.1.3, po aktualizacji do 1.2 wtyczka wciąż działała. Postaram się w tym tygodniu nad tym przysiąść i dłużej ją potestować.

**Comment by konradzdunczyk** [comment]
Zrobiłem PR z dodaniem temperatury, wilgotności i kilkoma innymi zmianami. Niestety, na ten moment HomeKit nie wspiera ciśnienia atmosferycznego.

https://github.com/bfaliszek/homebridge-smogomierz/pull/4

**Comment by hejsiri** [comment]
Tu masz mój sposób. https://github.com/bfaliszek/homebridge-smogomierz/issues/3

**Comment by konradzdunczyk** [comment]
> Tu masz mój sposób. #3

Na razie chciałem skorzystać z tego co już było i nie dodawać kolejnych zależności.

@mientki dlaczego nie dodałeś PR ze swoim rozwiązaniem?

BTW: Po moich zmianach dodanie obsługi MQTT po stronie kodu to kwestia napisania nowego Repository.

**Comment by bfaliszek** [comment]
@konradzdunczyk 
rozwiązanie z MQTT działa niezależnie od tej wtyczki. Tam musisz mieć broker MQTT. Smogomierz wysyła do niego dane pomiarowe. Jest inna wtyczka dla homebridge, która obsługuje MQTT.
Twoje rozwiązanie nie wymaga brokera MQTT jako pośrednika ;)

**Comment by hejsiri** [comment]
> @mientki dlaczego nie dodałeś PR ze swoim rozwiązaniem?

Co znaczy PR?

**Comment by bfaliszek** [comment]
@mientki PR - Pull Requests, czyli poprawił, przerobił i dopisał do mojego kodu swoje rzeczy i wysłał mi zapytanie, żebym je dodał. Przed chwilą to zrobiłem i jest już wersja wtyczki 1.3.0, która obsługuje PM2.5(jakość powietrza), temperaturę oraz wilgotność. Wszystko dzięki @konradzdunczyk! Wielkie dzięki!

**Comment by hejsiri** [comment]
Nie wiem jakie są procedury, ale podzieliłem się swoim rozwiązaniem, ale opartym na innej wtyczce, opierającej się na MQTT. 
@bfaliszek Swoją drogą ten mój wątek #3 powinien być otwarty bo się ukrywa, tylko nie wiem, jak mam to zrobić :) Zawsze się komuś przyda :)

**Comment by bfaliszek** [comment]
@mientki w najbliższym czasie chcę zaktualizować opisy i instrukcje dla osób składających Smogomierz. Dodam tak info o obu metodach dostępu do danych przez homebridge.

**Comment by bfaliszek** [comment]
Jest jeden plus rozwiązania z MQTT. Gdy mamy włączone deepsleep to przy wybudzeniu Smogomierz wyśle dane do brokera i wtyczka MQTT pobierze je sobie przy odświeżaniu danych.
W przypadku natywnej wtyczki homebridge nie mamy pośrednika, który pamięta ostatnie pomiary, więc nie pobierzemy danych, bo gdy Smogomierz jest uśpiony, bo nie ma wtedy dostępu do /api i danych pomiarowych.

**Comment by konradzdunczyk** [comment]
Jak będę miał wenę to dopiszę tryb MQTT do pluginu. Niby są pluginy do ogarniania MQTT, ale w ten sposób będzie bardziej out of the box
