### ISSUE TITLE
Plugin Smogomierz MQTT

### ISSUE THREAD

**Issue by hejsiri** [bfaliszek/homebridge-smogomierz#3]
Mam prawie działający plugin Smogomierza oparty na MQTT. Jedyne czego brakuje do pełni szczęścia to informacji ze smogomierza jaka jest jakość powietrza: UNKNOWN, EXCELLENT, GOOD, FAIR, INFERIOR lub POOR. Jeśli na brokerze zostanie opublikowany taki topic:

Smogomierz-xxxxxx/airquality

i jedna z poniższych wiadomości:

UNKNOWN
EXCELLENT
GOOD
FAIR
INFERIOR
POOR

To mamy gotowe rozwiązanie. Prośba do @bfaliszek :) o zaimplementowanie tego dodatkowego topica w wolnej chwili :) Oczywiście podzielę się swoim rozwiązaniem.

![6236B1CD-07F1-4B2E-A611-F37DA61F86F3](https://user-images.githubusercontent.com/37380727/56018877-98b82200-5d03-11e9-9fa7-f1bc04e52d78.png)
![F7359F14-2421-4FF3-9A29-3C516E16850D](https://user-images.githubusercontent.com/37380727/56018874-981f8b80-5d03-11e9-8973-20c077707174.png)
![C752A4BE-65C5-4CF5-8A39-F86634C916FD](https://user-images.githubusercontent.com/37380727/56018875-98b82200-5d03-11e9-9d4c-4a4ffc93da65.png)

**Comment by bfaliszek** [comment]
Bazując na http://www.eea.europa.eu/themes/air/air-quality-index
Proponuję oprzeć to na pomiarach PM2.5 i przyjąć takie wartości:
```
PM2.5 <= 10 - EXCELLENT
> 10 && PM25 <= 20 - GOOD
> 20 && PM25 <= 25 -  FAIR
> 25 && PM25 <= 50 - INFERIOR
> 50 - POOR
Jeśli z jakiegoś powodu warunki nie będą spełnione - UNKNOWN
```

**Comment by bfaliszek** [comment]
Właśnie dodałem to do kodu: https://github.com/hackerspace-silesia/Smogomierz/blob/a3ce0cf39718a95bfd7f139e76c50c1491ca6309/Smogomierz.ino#L612-L632
Jeśli mamy włączony jakikolwiek miernik PM, to poza wartościami liczbowymi, wysyłany będzie też komunikat o jakości powietrza. Warunki takie jak powyżej. Za kilka minut wrzucę też pliki .bin z 2.6.5 w którym jest już to dodane 😉

**Comment by bfaliszek** [comment]
https://github.com/hackerspace-silesia/Smogomierz/releases/tag/v2.6.5

**Comment by hejsiri** [comment]
Nie mogę wyjść z podziwu i uznania :) Dziękuję Ci bardzo :) Wrzucę dziś opis co i jak zrobić. Musze tylko znaleźć wolną chwilę.

**Comment by hejsiri** [comment]
A więc do wyświetlenia pomiarów w HomeKit ze smogomierza potrzebujemy plugin **mqttting**. 
https://github.com/arachnetech/homebridge-mqttthing

Moja konfiguracja wygląda tak:

```
        {
            "accessory": "mqttthing",
            "type": "airQualitySensor",
            "name": "Smogomierz Jakość powietrza",
            "url": "mqtt://localhost",
            "username": "user",
            "password": "pass",
            "logMqtt": "true",
            "topics": {
                "getAirQuality": "Smogomierz-8659439/airquality",
                "getPM10Density": "Smogomierz-8659439/sensor/PM10",
                "getPM2_5Density": "Smogomierz-8659439/sensor/PM2.5",
                "getCurrentTemperature": "Smogomierz-8659439/sensor/temperature",
                "getCurrentRelativeHumidity": "Smogomierz-8659439/sensor/humidity"
            },
            "history": "true"
        }
```


![IMG_2106](https://user-images.githubusercontent.com/37380727/56090600-93dea400-5ea4-11e9-8eb6-6bc66f7b832c.png)

**Comment by mientki** [comment]
test
